/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process liveness */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime readiness without contacting the LLM provider */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse and validate one Indonesian address */
        post: operations["parseAddress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ParseRequest: {
            text: string;
        };
        Address: {
            jalan: string | null;
            nomor: string | null;
            rt: string | null;
            rw: string | null;
            blok: string | null;
            unit: string | null;
            desa_kelurahan: string | null;
            kecamatan: string | null;
            kabupaten_kota: string | null;
            provinsi: string | null;
            kode_pos: string | null;
            patokan: string | null;
            penerima: string | null;
            kontak: string | null;
            catatan: string | null;
        };
        /** @enum {string} */
        MatchType: "exact" | "alias" | "fuzzy" | "inferred" | "none";
        AdminMatch: {
            input: string | null;
            code: string | null;
            name: string | null;
            match: components["schemas"]["MatchType"];
            /** Format: double */
            score: number;
        };
        AdminValidation: {
            desa_kelurahan: components["schemas"]["AdminMatch"];
            kecamatan: components["schemas"]["AdminMatch"];
            kabupaten_kota: components["schemas"]["AdminMatch"];
            provinsi: components["schemas"]["AdminMatch"];
        };
        /** @enum {string} */
        ValidationStatus: "valid" | "needs_clarification" | "invalid";
        Validation: {
            status: components["schemas"]["ValidationStatus"];
            admin: components["schemas"]["AdminValidation"];
        };
        /** @enum {string} */
        IssueCode: "MISSING_FIELD" | "UNKNOWN_REGION" | "AMBIGUOUS_REGION" | "HIERARCHY_MISMATCH" | "POSTAL_CODE_MISMATCH" | "POSTAL_CODE_UNKNOWN" | "NON_ADDRESS_INPUT";
        /** @enum {string} */
        Severity: "info" | "warning" | "error";
        Candidate: {
            code: string;
            name: string;
            parent: string | null;
        };
        Issue: {
            code: components["schemas"]["IssueCode"];
            field: string | null;
            severity: components["schemas"]["Severity"];
            message: string;
            candidates: components["schemas"]["Candidate"][];
        };
        ParseMetadata: {
            model: string;
            llm_attempts: number;
            /** Format: int64 */
            latency_ms: number;
            gazetteer_version: string;
        };
        ParseResponse: {
            request_id: string;
            address: components["schemas"]["Address"];
            validation: components["schemas"]["Validation"];
            issues: components["schemas"]["Issue"][];
            clarification_message: string | null;
            meta: components["schemas"]["ParseMetadata"];
        };
        /** @enum {string} */
        APIErrorCode: "INVALID_REQUEST" | "UNAUTHORIZED" | "PAYLOAD_TOO_LARGE" | "UNSUPPORTED_MEDIA_TYPE" | "VALIDATION_ERROR" | "TOO_BUSY" | "LLM_UPSTREAM_ERROR" | "LLM_UPSTREAM_RATE_LIMITED" | "LLM_TIMEOUT" | "LLM_INVALID_RESPONSE" | "SERVICE_NOT_READY" | "INTERNAL_ERROR";
        APIError: {
            code: components["schemas"]["APIErrorCode"];
            message: string;
            request_id: string;
        };
        APIErrorResponse: {
            error: components["schemas"]["APIError"];
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            version: string;
        };
        SourceMetadata: {
            source_name: string;
            /** @enum {string} */
            source_role: "official_benchmark" | "machine_readable_primary" | "cross_check" | "enrichment";
            commit_hash: string;
            license: string;
            /** Format: int64 */
            record_count: number;
        };
        ReadinessResponse: {
            /** @enum {string} */
            status: "ready" | "not_ready";
            version: string;
            llm_configured: boolean;
            gazetteer_ready: boolean;
            model: string;
            gazetteer_version: string;
            sources: components["schemas"]["SourceMetadata"][];
        };
    };
    responses: {
        /** @description Structured API error. */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service is not ready. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    parseAddress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRequest"];
            };
        };
        responses: {
            /** @description Address was processed. Inspect validation.status for the result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            413: components["responses"]["ErrorResponse"];
            415: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
            429: components["responses"]["ErrorResponse"];
            500: components["responses"]["ErrorResponse"];
            502: components["responses"]["ErrorResponse"];
            503: components["responses"]["ErrorResponse"];
            504: components["responses"]["ErrorResponse"];
        };
    };
}
